### ISSUE TITLE
Build assets without runtime dependencies.

### ISSUE THREAD

**Issue by jmalloc** [koshatul/goembed#3]
Would you consider a mode of operation whereby the generated code does have any non-stdlib dependencies?

**Comment by koshatul** [comment]
I would :)

I liked the use of a pseudo-filesystem, but a stdlib-only alternative might be a good option.

**Comment by jmalloc** [comment]
You could still keep it... "filesystemy" insofar as you could have an `func Open(path string) (io.ReadCloser, error)` function, but it'd also be useful to have direct access to the byte slices.

FYI, My use case for this has gone now, but it something I come across semi regularly for SQL schema.

**Comment by koshatul** [comment]
I've rewritten it and it no longer has runtime dependencies by default (the `wrapper` is selectable, either `nodep`s or `afero`).

Jobs done :)
